### ISSUE TITLE
Deployment hung?

### ISSUE THREAD

**Issue by nikmd23** [lostintangent/azjs#23]
![image](https://cloud.githubusercontent.com/assets/199026/26471449/61b7fd98-4167-11e7-8266-bced51f758e5.png)

I've been hung on the "Deploying code" process for a little over 10 mins now. 

The URL resolves to the default ApServices page:

![image](https://cloud.githubusercontent.com/assets/199026/26471498/8ddb8a3e-4167-11e7-860b-b4be8b7d2228.png)

The spinner is still spinning.

I'm using version `0.1.13` on Node `6.10.3` on Windows.

**Comment by lostintangent** [comment]
Can you try deleting the `node_modules` folder and running it again? Depending on the app, I can see this operation taking forever due to there being a ton of small files, and I need to add support for `azjs deploy` excluding certain folders to make sure its fast in all cases.

**Comment by lostintangent** [comment]
@nikmd23 I just published `0.1.14`, which (hopefully!) should address this issue, by ignoring the `node_modules` folder when zipping and deploying the app. Could you update and try again? :) 

It's entirely possible that there's another bug here, but I knew about the potential `node_modules` perf issue, so I wanted to fix that anyways, and see if that unblocks you.

**Comment by nikmd23** [comment]
As an FYI, I walked away from my machine, trying to let the operation finished.

It finally error-ed out, when my drive ran out of space. It looks like a 130 GB `.zip` file was created. 😆 

![azjs-error](https://cloud.githubusercontent.com/assets/199026/26498711/863cd420-41f5-11e7-85c0-9e2532d9a9e0.PNG)

This is probably a solved problem now that `node_modules` is excluded, but it might make sense to have a timeout/bail if things take a certain amount of time or disk space. I bet Azure has a limit on the file size that
can be uploaded anyways, so there's no point continuing to try once the `.zip` is larger than that.

I'll drop the file, update and try again.

**Comment by lostintangent** [comment]
Yeah that's a good idea. Let me know if the latest release unblocked you, and in parallel, I'll add more robust error handling for this scenario.

**Comment by nikmd23** [comment]
`0.1.14` did not seem to solve the problem. I canceled deployment process at about 25 mins/30 GB.

However, I did not delete the `node_modules` directory from my machine. I'll try that this time first.

**Comment by nikmd23** [comment]
I deleted modules and the deployment process completed!

Unfortunately, the site isn't working, and I'm not sure why. When I open the URL in a browser, I see an *The page cannot be displayed because an internal server error has occurred.* error message.

My sense is that this isn't an AzJs issue, rather an Azure configuration one, but I just don't know enough about how AzJs deploys the app to be sure. I'll try splunking through the SCM portal to see if I can find anything when I get some more time.

**Comment by lostintangent** [comment]
Hmm, I'll need to look into my fix, since that should have ignored the `node_modules` directory automatically. I'll make sure that is fixed for sure, but in the meantime, it seems like you are unblocked by just deleting it pre-deployment. That's great to know :)

After you run the deploy, and you see that error message, do you see any errors in the terminal? After running `azjs deploy`, it will open the log stream for the app, which should actually display an errors happening in the app post-deployment. 

Out of curiosity: what is the start script for the app you're deploying? Do you have a `start` script defined in your `package.json`? If not, what is the name of your startup file? It's possible that the logic that tries to infer your start script is also failing.

**Comment by nikmd23** [comment]
> After you run the deploy, and you see that error message, do you see any errors in the terminal? 

No, there were no errors in the terminal. The streaming log did start, and I got the minute by minute countdown until it timed out after 30 mins of inactivity. Which was awesome BTW.

There is a `start` script in my `package.json`. The scripts look like this:

```json
"scripts": {
  "build": "gulp",
  "clean": "gulp clean",
  "start": "node server/index.js"
}
```

To run the app locally, I simply call `npm start`. Is that problematic?

**Comment by lostintangent** [comment]
Hmm, OK. No, this should be good. In fact, the screenshot you included above even shows that `azjs` detected that `server/index.js` is your start file, so that seems to be correct, since that means it would run `node server/index.js` to run the app.

Does this app need to have `gulp` run on it before calling `npm start`? If so, then that would likely explain where the issue is, since `azjs` doesn't do anything beyond running `npm install` and then the equivalent of `npm start`. I could address this if that's the case, by simply detecting the presence of a `build` script in your `package.json` (I've been meaning to do this anyways), and run that as part of the deployment process.

**Comment by lostintangent** [comment]
I'm closing this issue based on confirming with @nikmd23 that the bug has been resolved. Please re-open if you see the problem again. Thanks!
